### PR TITLE
Choose pager command

### LINKED ISSUE #41: Add configuration for which pager to use
Currently the pager is using `more`. I don't have `more` set up to use repaint (`-R`) by default, so the output is without resolved color codes. I'd like to be able to configure the command used, in the event that I want to add the flag, use `less`, or use some other equivalent.

example output without `-R` for reference.

Screen Shot 2020-05-06 at 18 31 39

### PR DESCRIPTION
**Pull request by tiosgz**
This resolves #41

### CODE REVIEW

**Comment by tiosgz** [comment]
Now it should be OK, but it needs the setting to be migrated from boolean to command :-(

**Comment by iridakos** [comment]
@tiosgz :pray: 

I will check it a.s.a.p. and I will let you know.

Migration wise, we can add a note in README or even better, create a directory in the repo named `migrations` and add files for each version that would look like this:

```md
# file ./migrations/v-0.1.9.md

Find below the migrations you need to do after upgrading from 0.1.9 to a new version.

## 0.2.0

In version 0.2.0 the default `pager` blah blah blah.
You have to do blah bla bla
...
...
```

**Comment by sylvandb** [comment]
Instead of selecting a pager with configuration here, the typical standard is to use the PAGER env var (PAGER is a standard var like EDITOR and VISUAL). That means this fix should be instead to stop overwriting the PAGER var, use a different var such as USEPAGER for yes/no, and use PAGER if yes.

See `man 1 man` and also POSIX doc section 1 chapter 8: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_01

**Comment by iridakos** [comment]
@sylvandb thank you very much for your detailed information :rocket: 

@tiosgz sorry for taking too long to merge this, I've been busy these days. Hopefully I'll be able to check and merge it during this weekend. Thanks for your time and your great work on stup.

@all-contributors please add @sylvandb for review.

**Comment by tiosgz** [comment]
@iridakos I’m OK with delays as long as I know you don’t ignore me ;-) Just for case you wouldn’t notice it, there’s been more changes in how the pager config is treated:
* empty → `$PAGER`
* `false` → disabled
* anything else → use the value as pager

**Comment by iridakos** [comment]
IT'S ALIVE :tada: 

I've added an upgrade doc here: https://github.com/iridakos/stup/blob/master/documentation/upgrading/1.0.0.md

:pray:

**Pull request merged**
