### PR TITLE
Disable pager

### LINKED ISSUE #25: Disable pager
There should be a switch (`--[no-]pager`) and an option to enable/disable piping output to `more` where it's used.

### PR DESCRIPTION
**Pull request by tiosgz**
This resolves #25

### CODE REVIEW

**Comment by tiosgz** [comment]
I'm not sure if it's considered a bug that `configure` uses the switch (if present) instead of config file (could be changed by checking `$COMMAND` when applying the switch).

**Comment by iridakos** [comment]
> I'm not sure if it's considered a bug that configure uses the switch (if present) instead of config file (could be changed by checking $COMMAND when applying the switch).

I am not sure I understand the case. Can you give me an example?

(I checked out the code and it works super fine)

**Comment by tiosgz** [comment]
> I am not sure I understand the case. Can you give me an example?

1. let's say you have `pager=true` in the config
2. run `stup configure --no-pager`
3. when you come to the `pager` wizard, it says pager is disabled

and the same for the opposite. I haven't tested this, but quick thoughts tell me it should behave this way (see line 87 of https://github.com/iridakos/stup/pull/40/commits/ba1697534599231a101cc9cd9cc07cb6879e8b89).

**Comment by iridakos** [comment]
Nope, it works as expected. It shows the setting saved in the configuration file.

Bringing it in :) Thank you!

**Pull request merged**
